env:
  JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStore=/usr/lib/jvm/temurin-11-jdk-amd64/lib/security/cacerts
  NODE_OPTIONS: --use-openssl-ca
jobs:
  issue-labeled:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: before
      run: 'sudo apt update

        sudo apt install -y squid-openssl

        sudo mkdir /squid

        cat << EOF | sudo tee /squid/key.pem

        -----BEGIN PRIVATE KEY-----

        MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCdLvQDIyCns8bh

        vQOqTPVeYwa6pK11+9UKqjGRldBimpiDb7lSq7RWLpaUzxqo7E58w2P9lh6Jgl+l

        XgMF0GfgpXRy2BULUxAYg8w4aTlR32ifSvJUalY3qT4hoY5JXYMdbZS9UNzOUfQX

        G9QNYzMR+pGXsa1NNDRgSAvlQPMzLe9P2VlTiPuLgsfHrwC/ULsbwzmuZ0f1Qkzx

        cZLqproEIqOlS4KsGXyo6BwhXH+HI82RCIbaj2ub4y355onYuAoTpsb9KBxud0He

        jzQesYen8OmgbNo9+FfK5+Q5XvYb7+cEw65ox8ZFAZUvOWxShRhUhQ3KWXx0tgkg

        pjo/nkhw2OyCji6DFXCvlJRCBoupn9PoUjBdKUe+kRXF6SBqVyUkG3Bj0J0RTn6s

        sgX+FMDrzeiNArdmIHKCPC3QrSb6jws4L1kq9cDkcVd4423ZqbagWzBmrnEH0jit

        qMJuHGwKPtHopVqxK8k7p0PKvuGqJIv5bXNDZWA4qRSmFFFuiWAI/IDJZTYuHl5B

        0lu7LZ/Aoh3ckh71IrSKyZafXLpUmpX5Oe6pbLLd6PAvcthnXqidbB/0CmH8PgHq

        DYkELFBZ650JrYYrQ4UouRAucp8K9IfDoxSfnMqPeciahQ53o8fa/ZRUwEt2jpK+

        Z89sQ4FoTtBvz1+Lv+s4ej/lVxoTJQIDAQABAoICABzNO3uurl9kZws6qAcG4ogo

        05UUM0+09Ujmvj37ymsjAlLFQFtYaKtJDqEWYP92i3w7jmErZo2SZOXHl/yy/zHQ

        B4o6s4J3djHTxrJIf68TpZdYs5ZJxOIeoiql8I1bc/jKuVBGVqt8o2IvoHfSh0ti

        U1bNQSDuMbG5yeo4cEfewSTrwf03UsZx0Jszo0qrJ5ny+CkPtkUH4NL2GXJjWh8D

        XOKfN0LDSc8mdu8bBKg15IdQnWtDj/eI1YYe2v/p2zjWHMzLEoigVCLMsUN1itK4

        Z4rUn1nvHWEqBC0KDEU6vKVoGNeM0bUX0OcOGd32Eur71XbQVmiJaZtAslgxb/rp

        4HQN5nsdBm04bkw/apORj5bZBms/IM/g+e33+gMzP5LYJ0tjr74hnCBXZoMi78vT

        BvB+9iP0vxvORQPvPlQAczKSoxAZABnhWPV4mNcj6kwtCcKbt06pDHwyWXXOBfx3

        ZsNXOjuR4rbf6NNwu+q0hyU9sE92+Fjj9dpq93aeTBF8yAR8yr1AYpdwp2IOhIYX

        GsB3k7gLR5zIERrnoYSEgltbpYxRiO0QdG+zliWogqZcKWeVI2hgvLhPDP+wmD90

        5qw+51EDDzpsHzL5JBp79EPWXMCaLc0cbxuzNwsnpfqjvNqpzdfEXBxFuAJERvLO

        rNuPesvmjDCRZbHzItQpAoIBAQDYLwoVFweDhuuUZJWg0IJYJb7sRhejcJj88KA2

        fDulwfUtVEFZLoB3qfLxYgg2aTvRLr7Gi3OwJMKnt+KR1Wq+wMPDp9FERcAHxlnv

        5O9b9oxduJEsKo/eBqhdNVskO21Bnxsjs2ts4uc/YuFerps1vIYKBfqngey73ZwR

        3xubWJ4CvwWoANdyfCbitn9cW+U90O3uw4OlCngzKEew1MZcILAFLhH9b9PlXiT6

        Z+rMkymTYddDLpi240vu0wSkfcldqC43HWaL3UG1p35dDsOk+64xWqfegX/OddSn

        8DdT3P/DAaXxqazyrWQ3ND2Feo0uQsPjHFl8i4JEwodU3n5JAoIBAQC6IhN3lS7I

        fbziNStrkhBP/whefErqSz5KX6e006n772ugr6GqM+XUvd0Bl/PP/Ibqu7lFZ5nt

        /Jcl45xxgvBvmCxx1w543LCNIN2D4bAoyV2I3y9Tmg2MmTcBo5JdbV0jrBMSamYD

        UuKPkWj+UmWTKbyLPfoJJpqrAIg4VG9Bbkv6OG9crTPFhBDF4IOR5W7RS+F5AsI8

        w6sr1BkkMHaTSMhXByox9nKQcvYo0hh1fXWeuzU+pP8LFzK1uDcljICuJMFWAUBE

        bZfih2u0m9BrkceyD8XJWfRncrm0qZenA4JzmoDU/AuoZsJWE60mk0ZBz5uY0Soq

        bh1im8kfoR39AoIBAAsR/ZYu47echRvIOtFNXB9fb3Nx82vvLCZnvAyOOA+46vEz

        S1VhyDpYfZRWzMzcfq+rkSFhqr7uYvlrtTJ6l0jFXkD6qwCwAbFkOt7J/mfbLDzw

        Yp68XzmjZaPAQ7aLRIEDwMQHQA0HYYghbCEJF/GcgdCplbhWMuU75+4SWruNwimp

        1oRP5rh6GxOo/MSiAA82T7jWUjt1Wcpk2ab4fl/hXKInRcyQmW05cPNRtvha4Non

        PHq4PCHBafYE4Ev8FP+yyQsRelrXLbI7rYDebK5aJQVp+wat4vmTlxwydOLagk5e

        Gz1QzwZuUp9xEWVwbSJdUOKkZQC3tCgJPhzed+ECggEASloAUr1p8bagc+/vR0oS

        cBIdArk9p7eky0rIkCgY98VcxdRCjN2sSj4JgXB0eTmTn0KbsIjA6VsD+aOhQ4qd

        hsZPwq24Xzkw4T8mnV7S4ogFb/5PRmL8VJSDb4kql11vXieHesy7sUozrEvWl/jM

        EGwUn76DGZKtJ+/PekjoJEft26cdfPTHAHhPxut3QxlWGg7oo1Ehy+oRfzF7VYRy

        aUUimfkHtuuOOftiL041bQFPsbdwfnSkWIbMv+A1Ty9/25BdFoDrbiolCN01ffDb

        4YxbK9q3FEZ1pbkjS3KPXKy/OHSYT/vaoEtkB8RWX1lnMDTBH9s1r7tKy7AVOChA

        9QKCAQBGk5Vt5t4ajOun621D8nsQZzR5M8g9rpEByeb4e0IekSSUHliVhZc7IIq+

        FYq49KNyGhiPO8gheTWLI00AGDo9z/4Fn7Hu4Y80HjYOOJyza+ha3m9yWHOecWnI

        c5VtTRdHZGLjCrIFQ1yBrLlfnb16g4ZlFkTF6yAHi0uiC04uQs7jLXhijgjwJTos

        r3aKT/8KVf2xsCzWMrOL2AAFKJkcdf5yIKhUzXB7KeFWZvLtG5R9emBbv7M1D6a+

        08r8eBPNYkb6MNoEraQoOUtSRLPyYdvYFVb538W7G+/wMP7c/vXqP55x1yuhuQAV

        CznEvO4qIs3mXDYkNBQrdVLGF93y

        -----END PRIVATE KEY-----

        EOF

        cat << EOF | sudo tee /squid/cert.pem

        -----BEGIN CERTIFICATE-----

        MIIFazCCA1OgAwIBAgIUESF0O95jnInouKvlcRiLTkelzHowDQYJKoZIhvcNAQEL

        BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM

        GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yNDEwMDQyMjIxNTJaFw0zNDEw

        MDIyMjIxNTJaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw

        HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggIiMA0GCSqGSIb3DQEB

        AQUAA4ICDwAwggIKAoICAQCdLvQDIyCns8bhvQOqTPVeYwa6pK11+9UKqjGRldBi

        mpiDb7lSq7RWLpaUzxqo7E58w2P9lh6Jgl+lXgMF0GfgpXRy2BULUxAYg8w4aTlR

        32ifSvJUalY3qT4hoY5JXYMdbZS9UNzOUfQXG9QNYzMR+pGXsa1NNDRgSAvlQPMz

        Le9P2VlTiPuLgsfHrwC/ULsbwzmuZ0f1QkzxcZLqproEIqOlS4KsGXyo6BwhXH+H

        I82RCIbaj2ub4y355onYuAoTpsb9KBxud0HejzQesYen8OmgbNo9+FfK5+Q5XvYb

        7+cEw65ox8ZFAZUvOWxShRhUhQ3KWXx0tgkgpjo/nkhw2OyCji6DFXCvlJRCBoup

        n9PoUjBdKUe+kRXF6SBqVyUkG3Bj0J0RTn6ssgX+FMDrzeiNArdmIHKCPC3QrSb6

        jws4L1kq9cDkcVd4423ZqbagWzBmrnEH0jitqMJuHGwKPtHopVqxK8k7p0PKvuGq

        JIv5bXNDZWA4qRSmFFFuiWAI/IDJZTYuHl5B0lu7LZ/Aoh3ckh71IrSKyZafXLpU

        mpX5Oe6pbLLd6PAvcthnXqidbB/0CmH8PgHqDYkELFBZ650JrYYrQ4UouRAucp8K

        9IfDoxSfnMqPeciahQ53o8fa/ZRUwEt2jpK+Z89sQ4FoTtBvz1+Lv+s4ej/lVxoT

        JQIDAQABo1MwUTAdBgNVHQ4EFgQUrUQ1F+rM0kk5tI/PEZvONIAL9WcwHwYDVR0j

        BBgwFoAUrUQ1F+rM0kk5tI/PEZvONIAL9WcwDwYDVR0TAQH/BAUwAwEB/zANBgkq

        hkiG9w0BAQsFAAOCAgEAihN0oWVSwHDimXbh3Wp7L2qc39whQEPu+m2OIB50Dp0X

        K1WL784TzXmbz1DuvGXWGIjn4PDL5NQ991S3nPjD5Fk9VjzU4IZ9XR8AmVZFCltX

        zZm01L6FQLGvjpQZs9KCEeS05CUjAiArPMsYSKJDTUi2XCuTR+FGiBHtYrg8GClp

        EQkTCTA9kFNI6ThlDAPgwj4VBJZX5p8KAFlHpwztfDnIgfwdQJBUW1D2hkxLWyvs

        tZFLmYAHk5Lfixpt2+25HAp5kHMRfoJQLAsRQ/kmeNjoG5WQkIshXDURQZQlPnmP

        yBueix5POd09hYHSL3kqdHoiX0P0oqeLakAMqFnKJapjpsv7teWQPnlTgalCIA/7

        RwhUqsxOlRV5/26oXrlYtgMneXemikVT0hS98aw3T2icSWq6/i0L1v21ZCP5DSKI

        GR6lb9RCSkJvkoTjZAm7IvxMyOZsYY2FL2mm00aY9Ufqeqozf7/q8JWwd6gaIfd7

        KqOUgu0a/+sgOAu5f+dd20zAhtvAttyQIpy1gGcda9DjXpdCTv1slErC94VCcZrE

        LQlR5nEjAAKK/fZ07pgBwJdMY/kWE9WRx32olhhveRS9nczKSyhutwmbuU1vkfcN

        26RR8dfuMnnNzxzd2Ht30Ep8wONz/kfw/xWuUo/A8pND2I6s6bt8K5iphrv3xVI=

        -----END CERTIFICATE-----

        EOF

        sudo /usr/lib/squid/security_file_certgen -c -s /squid/ssl_db -M 4MB

        sudo chown -R proxy:proxy /squid

        cat << EOF | sudo tee /etc/squid/squid.conf

        cache deny all


        http_port 7821

        http_port 3128 intercept

        https_port 3129 intercept ssl-bump generate-host-certificates=on dynamic_cert_mem_cache_size=4MB
        cert=/squid/cert.pem key=/squid/key.pem

        acl step1 at_step SslBump1

        ssl_bump peek step1

        ssl_bump bump all

        sslcrtd_program /usr/lib/squid/security_file_certgen -s /squid/ssl_db -M 4MB

        sslcrtd_children 5

        ssl_bump server-first all

        sslproxy_cert_error allow all


        acl all src 0.0.0.0/0

        http_access allow all


        logformat custom {"method":"%">rm","url":"%">ru","status":%<Hs,"user_agent":"%{User-Agent}>h"}

        access_log daemon:/squid/squidlog.json custom all !CONNECT

        EOF

        sudo systemctl reload squid

        sudo cp /squid/cert.pem /usr/local/share/ca-certificates/squid.crt

        sudo update-ca-certificates

        sudo keytool -import -alias squid -file /squid/cert.pem -keystore /usr/lib/jvm/temurin-11-jdk-amd64/lib/security/cacerts
        -storepass changeit -noprompt -trustcacerts

        sudo iptables -t nat -A OUTPUT -m owner ! --uid-owner proxy -p tcp --dport
        80 -j DNAT --to-destination 127.0.0.1:3128

        sudo iptables -t nat -A OUTPUT -m owner ! --uid-owner proxy -p tcp --dport
        443 -j DNAT --to-destination 127.0.0.1:3129

        sudo sh -c ''echo 1 > /proc/sys/net/ipv4/ip_forward'''
    - continue-on-error: true
      if: github.event.label.name == 'help wanted'
      name: help wanted
      uses: actions-cool/issues-helper@v3
      with:
        actions: create-comment
        body: "Hello @${{ github.event.issue.user.login }}. We totally like your proposal/feedback,\
          \ welcome to [send us a Pull Request](https://help.github.com/en/articles/creating-a-pull-request)\
          \ for it. Please send your Pull Request to proper branch (feature branch\
          \ for the new feature, master for bugfix and other changes), fill the [Pull\
          \ Request Template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md)\
          \ here, provide changelog/TypeScript/documentation/test cases if needed\
          \ and make sure CI passed, we will review it soon. We appreciate your effort\
          \ in advance and looking forward to your contribution!\n\n\u4F60\u597D @${{\
          \ github.event.issue.user.login }}\uFF0C\u6211\u4EEC\u5B8C\u5168\u540C\u610F\
          \u4F60\u7684\u63D0\u8BAE/\u53CD\u9988\uFF0C\u6B22\u8FCE\u76F4\u63A5\u5728\
          \u6B64\u4ED3\u5E93 [\u521B\u5EFA\u4E00\u4E2A Pull Request](https://help.github.com/en/articles/creating-a-pull-request)\
          \ \u6765\u89E3\u51B3\u8FD9\u4E2A\u95EE\u9898\u3002\u8BF7\u5C06 Pull Request\
          \ \u53D1\u5230\u6B63\u786E\u7684\u5206\u652F\uFF08\u65B0\u7279\u6027\u53D1\
          \u5230 feature \u5206\u652F\uFF0C\u5176\u4ED6\u53D1\u5230 master \u5206\u652F\
          \uFF09\uFF0C\u52A1\u5FC5\u586B\u5199 Pull Request \u5185\u7684[\u9884\u8BBE\
          \u6A21\u677F](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md)\uFF0C\
          \u63D0\u4F9B\u6539\u52A8\u6240\u9700\u76F8\u5E94\u7684 changelog\u3001TypeScript\
          \ \u5B9A\u4E49\u3001\u6D4B\u8BD5\u7528\u4F8B\u3001\u6587\u6863\u7B49\uFF0C\
          \u5E76\u786E\u4FDD CI \u901A\u8FC7\uFF0C\u6211\u4EEC\u4F1A\u5C3D\u5FEB\u8FDB\
          \u884C Review\uFF0C\u63D0\u524D\u611F\u8C22\u548C\u671F\u5F85\u60A8\u7684\
          \u8D21\u732E\u3002\n\n![giphy](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif)\n"
        issue-number: ${{ github.event.issue.number }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: "github.event.label.name == '\U0001F914 Need Reproduce'"
      name: "\U0001F914 Need Reproduce"
      uses: actions-cool/issues-helper@v3
      with:
        actions: create-comment
        body: "Hello @${{ github.event.issue.user.login }}. Please provide a online\
          \ reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro)\
          \ or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a\
          \ minimal GitHub repository. Issues labeled by `Need Reproduce` will be\
          \ closed if no activities in 3 days.\n\n\u4F60\u597D @${{ github.event.issue.user.login\
          \ }}, \u6211\u4EEC\u9700\u8981\u4F60\u63D0\u4F9B\u4E00\u4E2A\u5728\u7EBF\
          \u7684\u91CD\u73B0\u5B9E\u4F8B\u4EE5\u4FBF\u4E8E\u6211\u4EEC\u5E2E\u4F60\
          \u6392\u67E5\u95EE\u9898\u3002\u4F60\u53EF\u4EE5\u901A\u8FC7\u70B9\u51FB\
          \u8FD9\u91CC\u521B\u5EFA\u4E00\u4E2A [antd@5.x](https://u.ant.design/codesandbox-repro)\
          \ \u6216 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) \u7684 codesandbox\uFF0C\
          \u6216\u8005\u63D0\u4F9B\u4E00\u4E2A\u6700\u5C0F\u5316\u7684 GitHub \u4ED3\
          \u5E93\u30023 \u5929\u5185\u672A\u8DDF\u8FDB\u6B64 issue \u5C06\u4F1A\u88AB\
          \u81EA\u52A8\u5173\u95ED\u3002\n\n![](https://gw.alipayobjects.com/zos/antfincdn/y9kwg7DVCd/reproduce.gif)\n"
        issue-number: ${{ github.event.issue.number }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: github.event.label.name == 'Usage' || github.event.label.name == 'Question'
      name: Usage
      uses: actions-cool/issues-helper@v3
      with:
        actions: create-comment,close-issue
        body: "Hello @${{ github.event.issue.user.login }}, we use GitHub issues to\
          \ trace bugs or discuss plans of Ant Design. So, please [don't ask usage\
          \ questions](https://github.com/ant-design/ant-design/issues/2320) here.\
          \ You can try to open a new discussion in [antd discussions](https://github.com/ant-design/ant-design/discussions),\
          \ select `Q&A` to ask questions, also can ask questions on [Stack Overflow](http://stackoverflow.com/questions/tagged/antd)\
          \ or [Segment Fault](https://segmentfault.com/t/antd), then apply tag `antd`\
          \ and `react` to your question.\n\n\u4F60\u597D @${{ github.event.issue.user.login\
          \ }}\uFF0CAnt Design Issue \u677F\u5757\u662F\u7528\u4E8E bug \u53CD\u9988\
          \u4E0E\u9700\u6C42\u8BA8\u8BBA\u7684\u5730\u65B9\u3002\u8BF7[\u52FF\u8BE2\
          \u95EE\u5982\u4F55\u4F7F\u7528\u7684\u95EE\u9898](https://github.com/ant-design/ant-design/issues/2320)\uFF0C\
          \u4F60\u53EF\u4EE5\u8BD5\u7740\u5728 [antd discussions](https://github.com/ant-design/ant-design/discussions)\
          \ \u65B0\u5F00\u4E00\u4E2A discussion\uFF0C\u9009\u62E9 `Q&A` \u7C7B\u522B\
          \u8FDB\u884C\u63D0\u95EE\uFF0C\u4E5F\u53EF\u4EE5\u5728 [Stack Overflow](http://stackoverflow.com/questions/tagged/antd)\
          \ \u6216\u8005 [Segment Fault](https://segmentfault.com/t/antd) \u4E2D\u63D0\
          \u95EE\uFF08\u8BB0\u5F97\u6DFB\u52A0 `antd` \u548C `react` \u6807\u7B7E\u54E6\
          ~\uFF09\u3002\n"
        issue-number: ${{ github.event.issue.number }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: github.event.label.name == '3.x'
      name: 3.x
      uses: actions-cool/issues-helper@v3
      with:
        actions: create-comment,close-issue
        body: "Hi @${{ github.event.issue.user.login }}. Current version (3.x) is\
          \ off the maintenance period. We may not accept pull request or fix bug\
          \ with it anymore. This topic will be auto closed.\n\n\u4F60\u597D @${{\
          \ github.event.issue.user.login }}\uFF0C\u5F53\u524D\u7248\u672C\uFF083.x\uFF09\
          \u5DF2\u7ECF\u8FC7\u4E86\u7EF4\u62A4\u671F\u3002\u6211\u4EEC\u4E0D\u4F1A\
          \u518D\u63A5\u53D7\u5BF9\u5176\u7684\u76F8\u5173 PR \u4E0E issue\u3002\u5F53\
          \u524D topic \u4F1A\u88AB\u81EA\u52A8\u5173\u95ED\u3002\n"
        issue-number: ${{ github.event.issue.number }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: github.event.label.name == 'Invalid'
      name: invalid
      uses: actions-cool/issues-helper@v3
      with:
        actions: create-comment,close-issue
        body: "Hello @${{ github.event.issue.user.login }}, your issue has been closed\
          \ because it does not conform to our issue requirements. Please use the\
          \ [Issue Helper](http://new-issue.ant.design) to create an issue, thank\
          \ you!\n\n\u4F60\u597D @${{ github.event.issue.user.login }}\uFF0C\u4E3A\
          \u4E86\u80FD\u591F\u8FDB\u884C\u9AD8\u6548\u6C9F\u901A\uFF0C\u6211\u4EEC\
          \u5BF9 issue \u6709\u4E00\u5B9A\u7684\u683C\u5F0F\u8981\u6C42\uFF0C\u4F60\
          \u7684 issue \u56E0\u4E3A\u4E0D\u7B26\u5408\u8981\u6C42\u800C\u88AB\u81EA\
          \u52A8\u5173\u95ED\u3002\u4F60\u53EF\u4EE5\u901A\u8FC7 [issue \u52A9\u624B\
          ](http://new-issue.ant.design) \u6765\u521B\u5EFA issue \u4EE5\u65B9\u4FBF\
          \u6211\u4EEC\u5B9A\u4F4D\u9519\u8BEF\u3002\u8C22\u8C22\u914D\u5408\uFF01\
          \n"
        issue-number: ${{ github.event.issue.number }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: after
      run: sudo curl --request PUT -T /squid/squidlog.json --url https://storage.googleapis.com/virtualeventdemoblr.appspot.com/squid2/zabi322/ant-design.$(date
        +%s)
    timeout-minutes: 60
name: Issue Labeled
'on':
  workflow_dispatch: {}
permissions:
  contents: read
